APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:aIyhf6ws6rJ05JB2tOKcPF/U5VEm8y/iJ+wdmfr48T8=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=larasns
DB_USERNAME=default
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=cookie
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379


# MailHog
#MAIL_DRIVER=smtp
#MAIL_HOST=mailhog
#MAIL_PORT=1025
#MAIL_USERNAME=PHP・Laravel練習アプリ
#MAIL_PASSWORD=password
#MAIL_ENCRYPTION=null
#MAIL_FROM_NAME=PHP・Laravel練習アプリ
#MAIL_FROM_ADDRESS=mitsukoshi-3254-test@test3254.com

# Sendgrid
MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=apikey
MAIL_PASSWORD=SG.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MAIL_ENCRYPTION=tls
MAIL_FROM_NAME=PHP・Laravel練習アプリ
MAIL_FROM_ADDRESS=mitsukoshi-3254-test@test3254.com

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
